In [60]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [61]:
!pip install pandas

import sys
sys.path.append("../")

# import joblib
import numpy as np
import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import Pipeline
# from sklearn.neural_network import MLPClassifier
# from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
# from umap import UMAP
# from ml import RPLandmarksTransformer
# from sklearn.preprocessing import OrdinalEncoder
# from sklearn.model_selection import GroupKFold

### Load results and estimators

In [62]:
landmarks = pd.read_csv("csv/ABIAS.csv")
x = landmarks[[col for col in landmarks.columns if "_x" in col]].T
y = landmarks[[col for col in landmarks.columns if "_y" in col]].T

In [63]:
x

0         1         2         3         4    \
hand_0_wrist_x           0.430396  0.431362  0.431172  0.431301  0.431106   
hand_0_thumb_cmc_x       0.460859  0.461214  0.461018  0.460570  0.460437   
hand_0_thumb_mcp_x       0.478049  0.477162  0.477110  0.476728  0.476434   
hand_0_thumb_ip_x        0.490347  0.488779  0.488509  0.488161  0.487796   
hand_0_thumb_tip_x       0.499638  0.497930  0.497526  0.497200  0.496755   
...                           ...       ...       ...       ...       ...   
pose_left_ankle_x        0.412198  0.412202  0.411374  0.411374  0.411158   
pose_right_heel_x        0.547717  0.547663  0.546284  0.546182  0.545911   
pose_left_heel_x         0.408671  0.408729  0.408194  0.408206  0.408099   
pose_right_foot_index_x  0.526476  0.526694  0.526341  0.526402  0.526376   
pose_left_foot_index_x   0.436790  0.436220  0.433511  0.433235  0.432713   

                              5         6         7         8         9    \
hand_0_wrist_x           0.431280  0.430894  0.430974  0.430986  0.430979   
hand_0_thumb_cmc_x       0.460395  0.460254  0.460259  0.460189  0.460320   
hand_0_thumb_mcp_x       0.476577  0.476337  0.476462  0.476271  0.476421   
hand_0_thumb_ip_x        0.488023  0.487716  0.487963  0.487713  0.487914   
hand_0_thumb_tip_x       0.497180  0.496715  0.497095  0.496764  0.496908   
...                           ...       ...       ...       ...       ...   
pose_left_ankle_x        0.411101  0.410781  0.410677  0.410585  0.410582   
pose_right_heel_x        0.545874  0.545398  0.545372  0.545358  0.545488   
pose_left_heel_x         0.408089  0.407936  0.407903  0.407860  0.407859   
pose_right_foot_index_x  0.526420  0.526253  0.526251  0.526244  0.526326   
pose_left_foot_index_x   0.432544  0.431856  0.431644  0.431497  0.431509   

                         ...       773       774       775       776  \
hand_0_wrist_x           ...  0.426949  0.426774  0.427353  0.428355   
hand_0_thumb_cmc_x       ...  0.456528  0.456546  0.456446  0.458171   
hand_0_thumb_mcp_x       ...  0.472451  0.472582  0.471656  0.473981   
hand_0_thumb_ip_x        ...  0.483486  0.483918  0.482401  0.485569   
hand_0_thumb_tip_x       ...  0.492643  0.493283  0.491072  0.495035   
...                      ...       ...       ...       ...       ...   
pose_left_ankle_x        ...  0.415779  0.416553  0.416799  0.416711   
pose_right_heel_x        ...  0.556371  0.556694  0.556911  0.556940   
pose_left_heel_x         ...  0.413891  0.414801  0.415017  0.414879   
pose_right_foot_index_x  ...  0.539193  0.539361  0.539456  0.539378   
pose_left_foot_index_x   ...  0.438647  0.439699  0.440025  0.439908   

                              777       778       779       780       781  \
hand_0_wrist_x           0.427854  0.427915  0.428163  0.429085  0.428928   
hand_0_thumb_cmc_x       0.457181  0.457934  0.458219  0.459287  0.458531   
hand_0_thumb_mcp_x       0.472713  0.473950  0.473706  0.475193  0.474251   
hand_0_thumb_ip_x        0.483756  0.485389  0.484660  0.486796  0.485360   
hand_0_thumb_tip_x       0.492627  0.494705  0.493315  0.496190  0.494344   
...                           ...       ...       ...       ...       ...   
pose_left_ankle_x        0.416699  0.416681  0.416639  0.416377  0.416191   
pose_right_heel_x        0.556982  0.556992  0.557000  0.556906  0.556847   
pose_left_heel_x         0.414857  0.414827  0.414766  0.414458  0.414241   
pose_right_foot_index_x  0.539364  0.539218  0.539042  0.538557  0.538146   
pose_left_foot_index_x   0.439866  0.439789  0.439676  0.439256  0.438948   

                              782  
hand_0_wrist_x           0.422332  
hand_0_thumb_cmc_x       0.451106  
hand_0_thumb_mcp_x       0.467268  
hand_0_thumb_ip_x        0.477800  
hand_0_thumb_tip_x       0.486221  
...                           ...  
pose_left_ankle_x        0.409686  
pose_right_heel_x        0.544901  
pose_left_heel_x         0.407730  
pose_right_foot_index_x  0.526

In [64]:
y

0         1         2         3         4    \
hand_0_wrist_y           0.788411  0.784486  0.785288  0.785288  0.785692   
hand_0_thumb_cmc_y       0.792772  0.790153  0.790359  0.791003  0.791008   
hand_0_thumb_mcp_y       0.775613  0.773247  0.773169  0.773780  0.773852   
hand_0_thumb_ip_y        0.765441  0.762131  0.761437  0.761953  0.761945   
hand_0_thumb_tip_y       0.755754  0.751750  0.749903  0.750262  0.750294   
...                           ...       ...       ...       ...       ...   
pose_left_ankle_y        1.701363  1.723281  1.735408  1.739057  1.741169   
pose_right_heel_y        1.761487  1.773882  1.783530  1.786794  1.789641   
pose_left_heel_y         1.752989  1.772637  1.784413  1.787939  1.789766   
pose_right_foot_index_y  1.825754  1.842400  1.852564  1.856788  1.859626   
pose_left_foot_index_y   1.826269  1.848742  1.860878  1.864486  1.866900   

                              5         6         7         8         9    \
hand_0_wrist_y           0.785960  0.785896  0.786226  0.786114  0.786165   
hand_0_thumb_cmc_y       0.791598  0.791341  0.792009  0.791924  0.791620   
hand_0_thumb_mcp_y       0.774272  0.774157  0.774984  0.774776  0.774483   
hand_0_thumb_ip_y        0.762445  0.762290  0.763302  0.763117  0.762715   
hand_0_thumb_tip_y       0.750558  0.750684  0.751621  0.751429  0.750957   
...                           ...       ...       ...       ...       ...   
pose_left_ankle_y        1.741578  1.742700  1.744249  1.744496  1.745412   
pose_right_heel_y        1.790138  1.791283  1.792703  1.792964  1.794008   
pose_left_heel_y         1.790137  1.791009  1.792408  1.792521  1.793516   
pose_right_foot_index_y  1.859770  1.860804  1.862384  1.862986  1.864451   
pose_left_foot_index_y   1.866896  1.868243  1.870119  1.870476  1.871635   

                         ...       773       774       775       776  \
hand_0_wrist_y           ...  0.809101  0.808526  0.805592  0.803393   
hand_0_thumb_cmc_y       ...  0.813515  0.813494  0.809873  0.808825   
hand_0_thumb_mcp_y       ...  0.794831  0.794730  0.791304  0.790506   
hand_0_thumb_ip_y        ...  0.781737  0.781628  0.777865  0.777930   
hand_0_thumb_tip_y       ...  0.769730  0.769929  0.767003  0.766279   
...                      ...       ...       ...       ...       ...   
pose_left_ankle_y        ...  1.820949  1.820879  1.820916  1.821030   
pose_right_heel_y        ...  1.860383  1.860246  1.860258  1.860235   
pose_left_heel_y         ...  1.867431  1.867378  1.867473  1.867702   
pose_right_foot_index_y  ...  1.940643  1.939819  1.939833  1.939875   
pose_left_foot_index_y   ...  1.953086  1.952825  1.952827  1.952891   

                              777       778       779       780       781  \
hand_0_wrist_y           0.802599  0.801605  0.802278  0.800659  0.800622   
hand_0_thumb_cmc_y       0.807216  0.808061  0.807223  0.805393  0.805382   
hand_0_thumb_mcp_y       0.788950  0.791339  0.789584  0.787819  0.787750   
hand_0_thumb_ip_y        0.776287  0.780258  0.777215  0.775909  0.775447   
hand_0_thumb_tip_y       0.764851  0.768944  0.765723  0.764814  0.764286   
...                           ...       ...       ...       ...       ...   
pose_left_ankle_y        1.821050  1.820967  1.820958  1.821044  1.821217   
pose_right_heel_y        1.859948  1.859436  1.859241  1.859214  1.859237   
pose_left_heel_y         1.867731  1.867754  1.867787  1.867996  1.868292   
pose_right_foot_index_y  1.939808  1.939613  1.939591  1.939599  1.939652   
pose_left_foot_index_y   1.952869  1.952664  1.952627  1.952718  1.952883   

                              782  
hand_0_wrist_y           0.778855  
hand_0_thumb_cmc_y       0.783511  
hand_0_thumb_mcp_y       0.764810  
hand_0_thumb_ip_y        0.751865  
hand_0_thumb_tip_y       0.738719  
...                           ...  
pose_left_ankle_y        1.821118  
pose_right_heel_y        1.860435  
pose_left_heel_y         1.868167  
pose_right_foot_index_y  1.939

In [65]:
x = x.to_numpy()
y = y.to_numpy()

## Pipeline

![Example Image](img/fig_paper.png)


In [57]:
print(f"N={x.shape[0]} (#landmarks)\nM={x.shape[1]} (#frames)")

N=541 (#landmarks)
M=783 (#frames)


In [97]:
X = np.array_split(x, x.shape[1]//3, axis=1)
Y = np.array_split(y, y.shape[1] // 3, axis=1)

X = np.stack(X, axis=1)

Y = np.stack(Y, axis=1)
X.shape

(541, 261, 3)

In [81]:
I = np.concatenate()

array([[[0.43039608, 0.43136239, 0.4311716 ],
        [0.43130106, 0.43110576, 0.43128037],
        [0.43089372, 0.43097377, 0.43098632],
        ...,
        [0.42677367, 0.42735335, 0.42835477],
        [0.42785367, 0.42791474, 0.42816335],
        [0.42908549, 0.42892775, 0.42233196]],

       [[0.46085918, 0.46121398, 0.46101788],
        [0.46057025, 0.46043661, 0.46039543],
        [0.46025392, 0.46025887, 0.46018934],
        ...,
        [0.4565458 , 0.45644563, 0.45817104],
        [0.45718145, 0.45793429, 0.45821914],
        [0.45928663, 0.45853099, 0.45110643]],

       [[0.4780485 , 0.47716174, 0.47710967],
        [0.47672841, 0.4764342 , 0.47657651],
        [0.47633716, 0.47646219, 0.47627148],
        ...,
        [0.4725818 , 0.47165614, 0.47398075],
        [0.47271302, 0.47395021, 0.47370604],
        [0.47519347, 0.47425121, 0.46726775]],

       ...,

       [[0.40867051, 0.40872893, 0.40819421],
        [0.4082064 , 0.40809932, 0.40808907],
        [0.40793633, 0

In [90]:
a = np.array([[0, 1], [2, 3], [4, 5]])
b = np.array([[6, 7], [8, 9], [10, 11]])
l = [a, b]
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [95]:
np.stack(l, axis=1)

array([[[ 0,  1],
        [ 6,  7]],

       [[ 2,  3],
        [ 8,  9]],

       [[ 4,  5],
        [10, 11]]])